apiVersion: v1
kind: ConfigMap
metadata:
  name: tezos-config
  namespace: "tqtezos"
data:
  parameters.json: |
    {
      "bootstrap_accounts": [
        [
          "edpkuwBYLUNKA18tdcnByxbxcfzKd5ddXiWe2TyhHoKHF6juHgdie8",
          "4000000000000"
        ],
        [
          "edpktezaD1wnUa5pT2pvj1JGHNey18WGhPc9fk9bbppD33KNQ2vH8R",
          "4000000000000"
        ]
      ],
      "preserved_cycles": 2,
      "blocks_per_cycle": 8,
      "blocks_per_commitment": 4,
      "blocks_per_roll_snapshot": 4,
      "blocks_per_voting_period": 64,
      "time_between_blocks": [
        "10",
        "20"
      ],
      "endorsers_per_block": 32,
      "hard_gas_limit_per_operation": "800000",
      "hard_gas_limit_per_block": "8000000",
      "proof_of_work_threshold": "-1",
      "tokens_per_roll": "8000000000",
      "michelson_maximum_type_size": 1000,
      "seed_nonce_revelation_tip": "125000",
      "origination_size": 257,
      "block_security_deposit": "512000000",
      "endorsement_security_deposit": "64000000",
      "endorsement_reward": [ "2000000" ],
      "cost_per_byte": "1000",
      "hard_storage_limit_per_operation": "60000",
      "test_chain_duration": "1966080",
      "quorum_min": 2000,
      "quorum_max": 7000,
      "min_proposal_quorum": 500,
      "initial_endorsers": 1,
      "delay_per_missing_endorsement": "1",
      "baking_reward_per_endorsement": [ "200000" ]
    }
  nodeconfig.json: |
    {
      "data-dir": "/var/tezos/node",
      "rpc": {
        "listen-addrs": [
          ":8733"
        ]
      },
      "p2p": {
        "bootstrap-peers": [
        ],
        "listen-addr": "[::]:8732"
      },
      "network": {
        "genesis": {
          "timestamp": "2019-11-21T17:43:32Z",
          "block": "BLockGenesisGenesisGenesisGenesisGenesisd1f7bcGMoXy",
          "protocol": "PtYuensgYBb3G3x1hLLbCmcav8ue8Kyd2khADcL5LsT5R1hcXex"
        },
        "genesis_parameters": {
          "values": {
            "genesis_pubkey": "edpktrQRy6X3VFv8gzALhKzapRcx3aTvH3vXuzFq8qPTJ8KDQ23fPe"
            }
        },
        "chain_name": "457a4d8a-aa4a-417b-a1a8-b8a7bd324666",
        "sandboxed_chain_name": "SANDBOXED_TEZOS",
        "default_bootstrap_peers": []
      }
    }
